micronaut:
  server:
    port: 8081
  application:
    name: lanchesSub
  cors:
    enabled: true
cassandra:
  default:
    basic:
      contact-points:
        - 127.0.0.1:9042
      session-keyspace: lanchonete
      load-balancing-policy:
        local-datacenter: datacenter1
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

nats.addresses:
  - nats://localhost:4222


#Para rodar o nats use esse dois trechos para ter uma imagem do docker
# docker pull nats
# docker run --name myScylla -p 9042:9042 --hostname local -d scylladb/scylla
# docker run -d --name nats-main -p 4222:4222 -p 6222:6222 -p 8222:8222 nats
# docker exec -it myScylla cqlsh
# CREATE KEYSPACE lanchonete WITH REPLICATION ={ 'class' : 'SimpleStrategy', 'replication_factor' : 1};
# use lanchonete;
# CREATE TABLE lanche (id UUID, nome TEXT, ingredientes TEXT, preco DOUBLE,PRIMARY KEY((id)));
